version: '3'
services:

  service:
    build: ./docker_compose/simple_project/app
    depends_on:
      - db
    expose:
      - "8000"
    env_file:
      - ./.env
    volumes:
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    depends_on:
      - service
    ports:
      - "80:80"

  theatre-db:
    image: postgres:16
    container_name: db_postgres_project
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project_collection
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data:
  static_value:
  media_value:
